pipeline {
    agent {
        node { label 'workstation' }
        }

    stages{

        stage('one') {
            steps {
                sh 'cd jenkins ; echo Hello'
                }
              }

      }

}