frontend:
	@echo installing frontend
catalouge:
	@echo installing cat
cart:
	@echo installing cart
user:
	@echo installing user
shipping:
	@echo installing ship
payment:
	@echo installing pay
mongodb:
	@echo installing mongo
redis:
	@echo installing redis
mysql:
	@echo installing mysql
rabbitmq:
	@echo installing rabbit
